### ISSUE TITLE
Please share Nvim config

### ISSUE THREAD

**Issue by YisusChrist** [Roshanpaudel111/Arch-Hyprland#11]
I would like to see your current nvim configuration, specially the [keyboard Ascii art](https://raw.githubusercontent.com/hyper-dot/Arch-Hyprland/main/assets/Screenshot_2023-10-14_22-59-13.png) you have (I guess it is custom, made by you). Any chance to share that publicly?

**Comment by hyper-dot** [comment]
@YisusChrist its in my repos. I appriciate you liked it. It was copied from somewhere on the internet. 😅

https://github.com/hyper-dot/nvim

**Comment by YisusChrist** [comment]
Thank you very much! ❤️
