### ISSUE TITLE
focus issue

### ISSUE THREAD

**Issue by joelschmol** [Roshanpaudel111/Arch-Hyprland#4]
When i open the rofi menu or the emoji one, it doesn't automatically focus on that menu. If I have another application open, I can just use my shortcut for switching focus and then switch focus to it, but if that's the first thing I'm opening, it doesn't work. I have to open an app and then switch to the rofi popup, otherwise it would just stay opened and I wouldn't be able to interact with it. The same happens with the emoji menu

**Comment by hyper-dot** [comment]
It's possible that the issue you're experiencing with the focus behavior of the Rofi menu and the emoji menu is related to Wayland. I am also facing exact same issue. I use `esc` to close rofi menus. Unfortunately I haven't find any solution for that.

**Comment by joelschmol** [comment]
Ahh man :(

**Comment by techsavvyumer** [comment]
facing exact same problem

**Comment by joelschmol** [comment]
I couldn't figure it out so i switched to wofi

**Comment by techsavvyumer** [comment]
@joelwoel I found the fix **[here](https://github.com/ChrisTitusTech/hyprland-titus/issues/13#issuecomment-1426870736)**

**Comment by joelschmol** [comment]
Thank you
