### ISSUE TITLE
waybar clock module doesnt work

### ISSUE THREAD

**Issue by Floppaboppa** [Roshanpaudel111/Arch-Hyprland#5]
every other module in waybar works except for the clock module, any help? im using the same waybar config file

**Comment by blazepwn** [comment]
Puede ser un error de alguna dependencia que necesites instalar como "libdate", si no funciona intenta utilizar un formato mas simple para tu widget de waybar:
"clock": {
    "format": "{:%I:%M %p}",
    "format-alt": "{:%a %b %d}",
    "tooltip-format": "<big>{:%B %Y}</big>\n<tt><small>{calendar}</small></tt>",
}

**Comment by Aguilar0607** [comment]
> every other module in waybar works except for the clock module, any help? im using the same waybar config file
Puede ser un error de alguna dependencia que necesites instalar como "libdate", si no funciona intenta utilizar un formato mas simple para tu widget de waybar:
"clock": {
"format": "{:%I:%M %p}",
"format-alt": "{:%a %b %d}",
"tooltip-format": "{:%B %Y}\n{calendar}",
}
