### ISSUE TITLE
What icons are used for waybar?

### ISSUE THREAD

**Issue by Cornelius-Figgle** [Roshanpaudel111/Arch-Hyprland#8]
I have `otf-font-awesome` installed and `ttf-jetbrains-mono ttf-jetbrains-mono-nerd noto-fonts-emoji` from the readme, but waybar still doesn't render all the icons correctly? Specifically, the CPU, Audio and WiFi icons are missing - am I missing a font somewhere?

![waybar icons](https://github.com/Roshanpaudel111/Arch-Hyprland/assets/110970234/fffa6e7d-81ef-4410-b51e-73f91b7642dc)

**Comment by hyper-dot** [comment]
Nerd fonts had issues recently. You can change the icons in `~/.config/waybar/config`. Just grab the icon you like from here : https://fontawesome.com/v5/cheatsheet  and then copy paste it in your config. 
I am not currently running hyprland. So its not being updated regularly. I suggest you to fork it and use it as your own version and constantly update it while you go.

**Comment by Cornelius-Figgle** [comment]
> Nerd fonts had issues recently

Ah okay, I will go find some more

> I suggest you to fork it and use it as your own version

I already was tbh, I didn't fork it but have copied bits of your setup into my own - this is my first Linux desktop setup, so I'm just changing bits until I like it, no where near finished yet

Thanks for the quick reply! ツ
